import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'

const inter = Inter({subsets: ['latin']})

export default function Home() { // get 1 March 2023 in seconds
    const launchDate = new Date('March 1, 2023 00:00:00').getTime() / 1000

    const [countdown, setCountdown] = useState(Math.round(launchDate - Date.now() / 1000))

    useEffect(() => {
        const interval = setInterval(() => {
            setCountdown(countdown - 1)
        }, 1000)
        return() => clearInterval(interval)
    })

    return (
        <>
            <Head>
                <title>Gamerplex Studio Melbourne</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous" />
            </Head>
            <main className={
                styles.main
            }>
                <div className={
                    styles.description
                }>
                    <div className={
                        styles.thirteen
                    }>
                        <h1>GAMERPLE<span className='x'>X</span></h1>

                    </div>
                    <div>
                        <a target="_blank" rel="noopener noreferrer">
                            Copyright © {
                            new Date().getFullYear()
                        }&nbsp;GAMERPLEX<span className='blink'>:</span>
                        </a>
                    </div>
                </div>

                <div>

                    
                    <p className='slogan'>
                        Scaling the Open Metaverse
                    </p>
                    <p className={
                        styles.center
                    }>
                        New website landing in&nbsp;
                        <code className={
                            styles.code
                        }>
                            {countdown} </code>
                        &nbsp;seconds.
                    </p>
                </div>

                <div>
                    <p className={
                        styles.center
                    }>
                        <button type="button" onclick={(e) => {e.preventDefault();      window.location.href='http://google.com';      }}>
                            <i class="fas fa-desktop"></i> Play on Web
                        </button>

                    </p>
                </div>

                <div className={
                    styles.grid
                }>
                    <a className={
                        styles.card
                    }>
                        <h2 className={
                            inter.className
                        }>
                            Multiple Games
                        </h2>
                        <p className={
                            inter.className
                        }>
                            Our ecosystem is standardising assets across multiple games
                        </p>
                    </a>

                    <a className={
                        styles.card
                    }>
                        <h2 className={
                            inter.className
                        }>
                            Shared Tokens
                        </h2>
                        <p className={
                            inter.className
                        }>
                            We are an avid member of the $KIN Ecosystem and believe in communities with shared value
                        </p>
                    </a>

                    <a className={
                        styles.card
                    }>
                        <h2 className={
                            inter.className
                        }>
                            Cross-game NFT's
                        </h2>
                        <p className={
                            inter.className
                        }>
                            We build game items using Solana & Raindrop NFT Standards
                        </p>
                    </a>

                    <a className={
                        styles.card
                    }>
                        <h2 className={
                            inter.className
                        }>
                            Open Standards
                        </h2>
                        <p className={
                            inter.className
                        }>
                            We are community focused on expanding the Solana Gaming community!
                        </p>
                    </a>
                        <a className={
                            styles.card
                        }></a>
                    <h3 className='heading'>Our Partners</h3>
                    <a className={
                        inter.className
                    }>Magic Eden</a>
                    <a className={
                        inter.className
                    }>Fractal</a>
                    <a className={
                        inter.className
                    }>Kin</a>
                    <br/>

                     <h3 className='heading'>Our Community</h3>
                    <a href='https://twitter.com/pet_legends' target='_blank' rel='noopener' className={
                        inter.className
                    }>Pet Legends</a>
                    <a href='https://gamerplex.com/discord' target='_blank' rel='noopener'  className={
                        inter.className
                    }>Discord</a>
                    <a href='https://twitter.com/gamerplex_com' target='_blank' rel='noopener' className={
                        inter.className
                    }>Twitter</a>
                    <br/>
                    <div>

                        <h3 className='heading'>Our Newsletter</h3>
                        <input type="text" placeholder="Email Address"/>
                        <button onClick={()=>confirm('Salim is the best?')}>Subscribe</button>
                    </div>
                </div>
            </main>
        </>
    )
}
